hiddenGems/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.conf.urls import handler404

urlpatterns = [
    path('admin/', admin.site.urls, ),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('basket/', include('basket.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('reviews/', include('reviews.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

handler404 = 'home.views.bad_request'

home/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='home'),
    path('404', views.view_404_page, name='404_page')
]

reviews/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('add/<int:product_id>/', views.add_review, name='add_review'),
    path('edit/<int:r_id>/', views.edit_review, name='edit_review'),
    path('delete/<int:r_id>/', views.delete_review, name='delete_review'),
]

reviews/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator


class Review(models.Model):
    product = models.ForeignKey('products.Product', null=True, blank=True, on_delete=models.SET_NULL)
    review_rating = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(5)],
                                        null=False, blank=False)
    user = models.CharField(max_length=254, null=False, blank=False, default="User not found")
    review_content = models.TextField(default="")

    def get_friendly_name(self):
        return self.review_rating

    def get_review_content(self):
        return self.review_content

reviews/forms.py
from django import forms
from .models import Review


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        exclude = ('user', 'product',)

    review_rating = forms.IntegerField(label='Rating / 5', widget=forms.NumberInput(attrs={'min': 0, 'max': 5,
                                                                                    'class': 'text-center'}))

reviews/views.py
from django.shortcuts import render, reverse, redirect, get_object_or_404
from .forms import ReviewForm
from .models import Review
from products.models import Product
from django.contrib import messages
from django.contrib.auth.decorators import login_required


@login_required
def add_review(request, product_id):
    if request.method == 'POST':
        form = ReviewForm(request.POST, request.FILES)
        if form.is_valid():
            user = request.user
            review_rating = form.cleaned_data.get("review_rating")
            review_content = form.cleaned_data.get("review_content")
            Review.objects.create(user=user, review_rating=review_rating,
                                  product=get_object_or_404(Product, pk=product_id),
                                  review_content=review_content)

            # retrieve data from current product
            retrieve_product = get_object_or_404(Product, pk=product_id)
            number_of_ratings = retrieve_product.number_of_ratings
            ratings_total = retrieve_product.rating_total

            # retrieving data from the form
            new_rating_score = form.cleaned_data.get("review_rating")

            # Average rating calculations
            # Adding up the total score of all the reviews
            retrieve_product.rating_total = ratings_total + new_rating_score

            # Adding 1 to the amount of reviews under the product
            retrieve_product.number_of_ratings = number_of_ratings + 1

            # Finding the average of the reviews
            retrieve_product.rating = retrieve_product.rating_total / retrieve_product.number_of_ratings
            retrieve_product.save()
            messages.success(request, 'Review added. Thank you!')
            return redirect(reverse('product_detail', args=[retrieve_product.id]))
        else:
            messages.error(request, "'Failed to add review.")
            return redirect(reverse('product_detail', args=[retrieve_product.id]))
    else:
        form = ReviewForm()
        product = get_object_or_404(Product, pk=product_id)
        template = 'reviews/add_review.html'
        context = {
                'form': form,
                'product': product,
        }
        return render(request, template, context)


@login_required
def edit_review(request, r_id):
    """ Edit a product in the store """

    ''' open review, get number, find rating, find difference, - difference from current total rating, save'''

    review = get_object_or_404(Review, pk=r_id)
    previous_review_rating = review.review_rating
    if request.method == 'POST':
        form = ReviewForm(request.POST, request.FILES, instance=review)
        if form.is_valid():

            product_id = review.product.id
            retrieve_product = get_object_or_404(Product, pk=product_id)

            new_review_rating = previous_review_rating - form.cleaned_data.get("review_rating")
            retrieve_product.rating_total = retrieve_product.rating_total - new_review_rating
            retrieve_product.rating = retrieve_product.rating_total / retrieve_product.number_of_ratings
            retrieve_product.save()

            messages.success(request, 'Successfully updated review!')
            review.review_content = form.cleaned_data.get("review_content")
            review.review_rating = form.cleaned_data.get("review_rating")
            review.save()
            return redirect('profile')
        else:
            messages.error(request, 'Failed to update review. Please ensure the form is valid.')
            return redirect('profile')
    else:
        form = ReviewForm(instance=review)
        template = 'reviews/edit_reviews.html'
        context = {
            'form': form,
            'r': review,
        }

        return render(request, template, context)


@login_required
def delete_review(request, r_id):
    # retrieve the review and product to manipulate both
    review = get_object_or_404(Review, pk=r_id)
    product = get_object_or_404(Product, name=review.product)

    # Calculating the new rating scores.
    product.number_of_ratings = product.number_of_ratings - 1

    product.rating_total = product.rating_total - review.review_rating

    if product.number_of_ratings != 0:
        product.rating = product.rating_total / product.number_of_ratings
    else:
        product.rating = 0
    review.delete()
    product.save()
    messages.success(request, 'Review deleted!')
    return redirect(reverse('profile'))

reviews/templates/reviews/add_review.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container main-section-container margin-header-wrapper">
    <div class="row">
        <div class="col-12">
            {% if messages %}
                <div class="message-container">
                    {% for message in messages %}
                        {% with message.level as level %}
                            <p class="mb-0">
                                {% if level == 25 %}
                                    <i class="far fa-check-circle"></i> 
                                {% endif %}
                                {{message}}
                            </p>
                        {% endwith %}
                    {% endfor %}
                </div>
            {% endif %}
        </div>

        <div class="col-12 text-center extra-margin-top ">
            <hr>
            <h2 class="logo-font">Add Review</h2>
            <hr>
        </div>
    </div>
    <div class="row ">
        <div class="col-12 col-md-10 offset-md-1 text-center extra-margin-bottom">
            <form method="POST" action="{% url 'add_review' product.id %}" class="form mb-2" enctype="multipart/form-data">
                {% csrf_token %}
                <label for="add_review_rating" class=" requiredField">Rating / 5<span class="asteriskField">*</span> </label>
                <div class="input-group mb-3">
                    <div class="btn" id="decreaseAddReviewQuantity">
                            <span><i class="fas fa-minus fa-sm"></i></span>
                        </div>  
                       <input type="number" name="review_rating" value="0" min="0" max="5" class="text-center numberinput form-control" required="" id="add_review_rating">
                        <div class="btn" id="increaseAddReviewQuantity" >
                            <span><i class="fas fa-plus fa-sm"></i></span>
                        </div>
                    </div>

                    <label for="id_review_content" class=" requiredField"> Review content<span class="asteriskField">*</span> </label>
                    <div class="input-group mb-3">
                        <textarea name="review_content" cols="40" rows="10" class="textarea form-control" required="" id="id_review_content" value="{{r.review_content}}">{{r.review_content}}</textarea>
                     </div>

                    <div class="text-center extra-margin-bottom extra-margin-top">
                        <div>
                            <button class="btn action-btn btn-lg rounded-0 mb-3 col-12 col-lg-6 " type="submit">Add Review <i class="fas fa-chevron-right"></i> </button>
                        </div>
                    <div>
                        <a class="btn second-btn btn-lg rounded-0 mb-2 col-12 col-lg-6" href="{% url 'product_detail' product.id %}"><i class="fas fa-chevron-left"></i>  Cancel</a>
                    </div> 
                </div>    
            </form>
        </div>
    </div>
</div>
{% include 'includes/footer.html' %}
{% endblock %}

reviews/templates/reviews/edit_reviews.html
{% extends "base.html" %}
{% load static %}


{% block content %}
 
    <div class="container main-section-container margin-header-wrapper">
        <div class="row">
            <div class="col-12 text-center extra-margin-top">
                <hr>
                <h2 class="logo-font">Edit Review</h2>
                <hr>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-md-10 offset-md-1 extra-margin-bottom">
                <form method="POST" action="{% url 'edit_review' r.id %}" class="form mb-2 text-center" enctype="multipart/form-data">
                    {% csrf_token %}
                    <label for="edit_review_rating" class=" requiredField">Rating / 5<span class="asteriskField">*</span> </label>
                    <div class="input-group mb-3">
                    
                        <div class="btn" id="decreaseEditReviewQuantity">
                                <span><i class="fas fa-minus fa-sm"></i></span>
                        </div>  
                        <input type="number" name="review_rating" value="{{r.review_rating}}" min="0" max="5" class="text-center numberinput form-control" required="" id="edit_review_rating">
                        <div class="btn" id="increaseEditReviewQuantity" >
                            <span><i class="fas fa-plus fa-sm"></i></span>
                        </div>
                    </div>


                    <label for="id_review_content" class=" requiredField">Review content<span class="asteriskField">*</span> </label>
                    <div class="input-group mb-3">
                        <textarea name="review_content" cols="40" rows="10" class="textarea form-control" required="" id="id_review_content" value="{{r.review_content}}">{{r.review_content}}</textarea>
                    </div>
                    
                    <div class="text-center extra-margin-bottom extra-margin-top">
                        <div>
                            <button class="btn action-btn btn-lg rounded-0 mb-3 col-12" type="submit">Update Review <i class="fas fa-chevron-right"></i> </button>
                        </div>
                        <div>
                            <a class="btn second-btn btn-lg mb-2 rounded-0 col-12" href="{% url 'profile' %}"><i class="fas fa-chevron-left"></i>  Cancel</a>
                        </div>                        
                    </div>
                </form>
            </div>            
        </div>
    </div>
    {% include 'includes/footer.html' %}
    
{% endblock %}